### ISSUE TITLE
Estudo básico

### ISSUE THREAD

**Issue by holyvieri** [saphoi/echotext#2]
- [x] Divisão de branchs por funcionalidade ou por dev
- [x] Definir linguagem front-end: React?
- [x] Definir o padrão de arquitetura 
- [x] Verificar necessidade de Vercel 
- [x] Falar com o professor Elisson sobre o projeto: BD - Seria necessario para fotos ou só se usar login?

**Comment by paulabeatrizz** [comment]
FastAPI e flask

**Comment by holyvieri** [comment]
> * [x]  Divisão de branchs por funcionalidade ou por dev
> * [x]  Definir linguagem front-end: React?
> * [ ]  Definir o padrão de arquitetura
> * [ ]  Verificar necessidade de Vercel
> * [x]  Falar com o professor Elisson sobre o projeto: BD - Seria necessario para fotos ou só se usar login?

- sugestão: funcionalidade 
- criar branchs tipo: back, front, teste, ...
- front pode sim ser com react ou fzr html+css+js
- arquitetura ? 
- recomendação do back: FastAPI ou Flask (PYTHON)

**Comment by holyvieri** [comment]
a arq vai ser mvc msm
